database:
  dsn: "TKC UAT"
  username: "iuctclient"
  password: "xXZHaii7"

  postgresql:
    host: 10.210.22.130
    port: 5432
    user: airflow
    password: airflow
    database: oncopole_test

  clickhouse:
    host: 10.210.22.130
    port: 18123
    username: default
    password: ''

  oracle:
    user: "DATA_LECTURE"
    password: "Data_Lecture_31!"
    dsn: "10.220.1.199:1521/DWHP19"
    encoding: "UTF-8"
