me: Deploy minimal-dataset
on:
  push:
    branches:
      - POC_1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy files to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Chemin de destination sur le serveur
            TARGET_DIR=~/airflow/dags/minimal-dataset

            # Supprimer l'ancien contenu (optionnel)
            rm -rf $TARGET_DIR/*

            # Copier le contenu du repo GitHub
            cp -r $GITHUB_WORKSPACE/* $TARGET_DIR/

            # Afficher le contenu pour vérification
            ls -la $TARGET_DIR

