name: Déploiement SSH

on:
  push:
    branches:
      - POC_1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Déployer via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}         # IP ou hostname du serveur
          username: ${{ secrets.SSH_USER }}     # utilisateur SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # clé privée
          port: 22                               # port SSH
          source: "./"                           # dossier local à copier (repo)
          target: "~/airflow/dags/minimal-dataset"  # dossier cible sur le serveur
          rm: true                               # supprime le contenu cible avant copie
          debug: true                            # affiche les logs détaillés pour debug


