name: ETL Oncopole CI + Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 . --exclude=__pycache__,config,utils/patients.py --max-line-length=120

      - name: Run tests with pytest
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          if [ -d "tests" ]; then pytest tests/; else echo "No tests directory."; fi

  deploy:
    name: Deploy to Airflow Server
    needs: lint-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copier les fichiers du projet vers le dossier Airflow
        run: |
          cp -r utils ~/airflow/dags/
          cp -r sql ~/airflow/dags/
          cp -r tests ~/airflow/dags/
          cp etl_*.py ~/airflow/dags/
          cp requirements.txt ~/airflow/dags/

      - name: Restart Airflow
        run: |
          pkill -f "airflow webserver" || true
          pkill -f "airflow scheduler" || true
          nohup airflow webserver --daemon > ~/airflow/airflow-webserver.out 2>&1 &
          nohup airflow scheduler --daemon > ~/airflow/airflow-scheduler.out 2>&1 &

      - name: Afficher le chemin courant
        run: |
          echo "Répertoire courant : $(pwd)"
          ls -la

      - name: Afficher variables d'environnement
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "HOME=$HOME"
