name: Déploiement Local via Runner

on:
  push:
    branches:
      - POC_1

jobs:
  deploy:
    # On cible votre runner local "CliDataDSIN"
    runs-on: self-hosted

    steps:
      # Étape 1 : Récupérer le code source du repo GitHub sur la machine
      - name: Checkout du repo
        uses: actions/checkout@v4

      # Étape 2 : Déployer les fichiers vers le dossier Airflow local
      - name: Mise à jour des DAGs Airflow
        run: |
          # Création du dossier cible s'il n'existe pas
          mkdir -p /home/administrateur/airflow/dags/minimal-dataset
          
          # Nettoyage du dossier avant la copie pour éviter les vieux fichiers
          rm -rf /home/administrateur/airflow/dags/minimal-dataset/*
          
          # Copie de tout le contenu du repo vers le dossier Airflow
          # Le "." représente le dossier où le runner a téléchargé votre code
          cp -r ./* /home/administrateur/airflow/dags/minimal-dataset/
          
          echo "Le déploiement sur la branche POC_1 a réussi."
          
          sudo systemctl restart airflow-webserver
          sudo systemctl restart airflow-scheduler
          
          echo "Le déploiement et le redémarrage des services ont été effectués."